### ISSUE TITLE
MNA-001 Subscription

### ISSUE THREAD

**Issue by toegl** [sw21-tug/Team_09#1]
**As an** app user
**I want to** subscribe to a newsgroup server
**So that** I can see the subgroups from this server

Acceptance Criteria: 
- [x] Subscription to a newsgroup works as expected
- [x] Hierarchy and list of all subgroups is shown
- [x] Works without login

**Comment by jakobdunst** [comment]
related issues/tasks:
#21 
#22 
#27 
#32

**Comment by toegl** [comment]
Everything works fine.
